// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TbImportRun struct {
	ID           uuid.UUID
	SourceSystem string
	StartedAt    pgtype.Timestamptz
	FinishedAt   pgtype.Timestamptz
	Status       string
	ErrorMessage pgtype.Text
}

type TbJournal struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type TbJourney struct {
	ID             uuid.UUID
	JournalID      uuid.UUID
	Slug           string
	SourceRef      pgtype.Text
	Title          string
	Place          string
	Country        pgtype.Text
	Region         pgtype.Text
	DateStart      pgtype.Date
	DateEnd        pgtype.Date
	GpsRoute       interface{}
	AuthoredFields []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type TbMemento struct {
	ID               uuid.UUID
	JourneyID        uuid.UUID
	Kind             string
	Seq              int32
	OccurredAt       pgtype.Timestamptz
	OccurredTz       pgtype.Text
	Geom             interface{}
	Title            pgtype.Text
	Place            pgtype.Text
	Vendor           pgtype.Text
	Essay            pgtype.Text
	PriceAmount      pgtype.Int8
	PriceCurrency    pgtype.Text
	KindData         []byte
	SourceRef        pgtype.Text
	AuthoredFields   []string
	OrphanedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	State            string
	SourceSystem     pgtype.Text
	SourceExternalID pgtype.Text
	Revision         int64
}

type TbMementoPhoto struct {
	ID          uuid.UUID
	MementoID   uuid.UUID
	ObjectKey   string
	ContentHash string
	Caption     pgtype.Text
	Seq         int32
	TakenAt     pgtype.Timestamptz
	SourceRef   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type TbSourceObservation struct {
	ID               uuid.UUID
	RunID            uuid.UUID
	SourceSystem     string
	SourceExternalID string
	Kind             string
	ObservedAt       pgtype.Timestamptz
	Confidence       float64
	Payload          []byte
	Changed          bool
	OrphanedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type TbStopCandidate struct {
	ID                uuid.UUID
	JourneyID         uuid.UUID
	DerivationVersion string
	CandidateKey      string
	Label             string
	AuthoredFields    []string
	Geom              interface{}
	Arrive            pgtype.Timestamptz
	Depart            pgtype.Timestamptz
	Confidence        float64
	State             string
	MergedInto        pgtype.UUID
	Provenance        []byte
	Revision          int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type TbStopCandidateEvidence struct {
	ID               uuid.UUID
	CandidateID      uuid.UUID
	Kind             string
	SourceSystem     string
	SourceExternalID string
	Locator          string
}

type TbTransitLeg struct {
	ID          uuid.UUID
	JourneyID   uuid.UUID
	Seq         int32
	OriginLabel pgtype.Text
	DestLabel   pgtype.Text
	Geom        interface{}
	CreatedAt   pgtype.Timestamptz
}
