import { test, expect } from "./fixtures"

test("slug collision retains input and retry creates a separate journey", async ({ page }) => {
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  const original = { title: "Original synthetic trip", place: "Kyoto", slug: "reserved-slug", date_start: "2026-05-01", date_end: "2026-05-03" }
  const seed = await page.request.post("/api/admin/journeys", { data: original })
  expect(seed.status()).toBe(200)
  await page.goto("/")
  await page.getByRole("button", { name: "New journey", exact: true }).click()
  const sheet = page.getByRole("dialog")
  await sheet.getByLabel("Title", { exact: true }).fill("New synthetic trip")
  await sheet.getByLabel("Place", { exact: true }).fill("Osaka")
  await sheet.getByLabel("Start date", { exact: true }).fill("2026-05-01")
  await sheet.getByLabel("End date", { exact: true }).fill("2026-05-03")
  await sheet.getByText("More options", { exact: true }).click()
  await sheet.getByLabel("Slug", { exact: true }).fill("reserved-slug")
  const rejected = page.waitForResponse((response) => response.url().endsWith("/api/admin/journeys") && response.request().method() === "POST")
  await sheet.getByRole("button", { name: "Create journey", exact: true }).click()
  expect((await rejected).status()).toBe(409)
  await expect(sheet.getByRole("alert")).toContainText("Choose another slug")
  await expect(sheet.getByLabel("Title", { exact: true })).toHaveValue("New synthetic trip")
  await expect(sheet.getByLabel("Place", { exact: true })).toHaveValue("Osaka")
  await expect(sheet.getByLabel("Start date", { exact: true })).toHaveValue("2026-05-01")
  const rows = await (await page.request.get("/api/admin/journeys")).json()
  expect(rows).toHaveLength(1)
  expect(rows[0].title).toBe(original.title)
  await sheet.getByLabel("Slug", { exact: true }).fill("separate-synthetic-trip")
  await sheet.getByRole("button", { name: "Create journey", exact: true }).click()
  await expect(page.getByRole("heading", { name: "New synthetic trip", exact: true })).toBeVisible()
  expect(await (await page.request.get("/api/admin/journeys")).json()).toHaveLength(2)
  expect(errors).toEqual([])
})
