import { test, expect } from "./fixtures"

for (const width of [1100, 720]) {
  test(`icon actions expose names and hover/focus hints at ${width}px`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 760 })
    await page.goto("/")
    const settings = page.getByRole("button", { name: "Settings", exact: true })
    await expect(settings).toHaveText("")
    await expect(settings.locator('svg[aria-hidden="true"]')).toHaveCount(1)
    await settings.hover()
    await expect(page.getByRole("tooltip")).toHaveText("Settings")
    await page.keyboard.press("Escape")
    await expect(page.getByRole("tooltip")).toBeHidden()

    // Exercise actual keyboard focus, not a programmatic focus assertion.
    await page.getByRole("link", { name: "Site & Deploy", exact: true }).focus()
    await page.keyboard.press("Tab")
    await expect(settings).toBeFocused()
    await expect(page.getByRole("tooltip")).toHaveText("Settings")
    await page.keyboard.press("Enter")
    await expect(page.getByRole("dialog", { name: "Settings", exact: true })).toBeVisible()
    await expect(page.getByRole("tooltip")).toBeHidden()
    await page.keyboard.press("Escape")
    await expect(settings).toBeFocused()
    await expect(page.getByRole("dialog", { name: "Settings", exact: true })).toBeHidden()

    const scan = page.getByRole("button", { name: "Scan trip folder", exact: true })
    await expect(scan).toHaveText("Scan")
    await expect(scan.locator('svg[aria-hidden="true"]')).toHaveCount(1)
    const create = page.getByRole("button", { name: "New journey", exact: true })
    await expect(create.locator('svg[aria-hidden="true"]')).toHaveCount(1)

    await page.goto("/#/site")
    const folder = page.getByRole("button", { name: "Change location…", exact: true })
    await expect(folder).toHaveText("")
    await folder.hover()
    await expect(page.getByRole("tooltip")).toHaveText("Change location…")
    const box = await folder.boundingBox()
    expect(box!.width).toBeGreaterThanOrEqual(24)
    expect(box!.height).toBeGreaterThanOrEqual(24)
    expect(box!.x + box!.width).toBeLessThanOrEqual(width)
    const build = page.getByRole("button", { name: "Build site", exact: true })
    await expect(build).toHaveText("Build")
    await expect(build.locator('svg[aria-hidden="true"]')).toHaveCount(1)
    const save = page.getByRole("button", { name: "Save site settings", exact: true })
    await expect(save).toHaveText("Save")
    await expect(save.locator('svg[aria-hidden="true"]')).toHaveCount(1)
    await page.screenshot({ path: info.outputPath(`site-icons-${width}.png`) })

    // The existing picker callback still runs. Desktop folder-list API parity
    // is separate; this check does not claim native picker acceptance.
    await folder.click()
    const picker = page.getByRole("dialog", { name: "Choose output location", exact: true })
    await expect(picker).toBeVisible()
    const close = picker.getByRole("button", { name: "Close", exact: true })
    await expect(close).toHaveText("")
    await close.click()
    await expect(picker).toBeHidden()
    await expect(folder).toBeFocused()
  })
}

test("journey Back is an icon-only native link with hover and keyboard hints", async ({ page }) => {
  await page.goto("/")
  await expect(page.getByRole("heading", { name: "Journeys", exact: true })).toBeVisible()
  const response = await page.request.post("/api/admin/journeys", {
    data: { slug: "icon-navigation", title: "Icon navigation", place: "Synthetic city", date_start: "2026-03-20", date_end: "2026-03-21" },
  })
  expect(response.ok()).toBe(true)
  const { id } = await response.json()
  await page.goto(`/#/journey/${id}`)
  const back = page.getByRole("link", { name: "Back to journeys", exact: true })
  await expect(back).toHaveAttribute("href", "#/")
  await expect(back).toHaveText("")
  await expect(back.locator('svg[aria-hidden="true"]')).toHaveCount(1)
  await back.hover()
  await expect(page.getByRole("tooltip")).toHaveText("Back to journeys")
  await page.getByRole("button", { name: "Settings", exact: true }).focus()
  await page.keyboard.press("Tab")
  await expect(back).toBeFocused()
  await expect(page.getByRole("tooltip")).toHaveText("Back to journeys")
  await page.keyboard.press("Enter")
  await expect(page.getByRole("heading", { name: "Journeys", exact: true })).toBeVisible()
})

test("modal Close hint renders inside the top layer and preserves cancellation", async ({ page }) => {
  await page.goto("/")
  const create = page.getByRole("button", { name: "New journey", exact: true })
  await create.click()
  const sheet = page.getByRole("dialog", { name: "Create a new journey", exact: true })
  const close = sheet.getByRole("button", { name: "Close", exact: true })
  await expect(close).toHaveText("")
  await close.hover()
  const hint = sheet.getByRole("tooltip")
  await expect(hint).toHaveText("Close")
  await expect(hint).toBeVisible()
  await expect(hint).toBeInViewport()
  await close.click()
  await expect(sheet).toBeHidden()
  await expect(create).toBeFocused()
  const journeys = await page.request.get("/api/admin/journeys")
  expect(await journeys.json()).toEqual([])
})
