import { test, expect } from "./fixtures"

test.use({ sampleMode: true, userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/605.1.15 wails.io" })

test("native shell loads the matching drag runtime and keeps controls non-draggable", async ({ page }) => {
  await page.route("**/wails/runtime.js", (route) => route.fulfill({ contentType: "application/javascript", body: "" }))
  await page.goto("/")
  await expect(page.locator('script[src="/wails/runtime.js"]')).toHaveCount(1)
  expect(await page.locator(".window-toolbar").evaluate((element) => getComputedStyle(element).getPropertyValue("--wails-draggable").trim())).toBe("drag")
  expect(await page.getByRole("button", { name: "New journey", exact: true }).evaluate((element) => getComputedStyle(element).getPropertyValue("--wails-draggable").trim())).toBe("no-drag")
  await page.getByRole("button", { name: "New journey", exact: true }).click()
  await expect(page.locator('script[src="/wails/runtime.js"]')).toHaveCount(1)
  await expect(page.getByLabel("Title", { exact: true })).toBeFocused()
})

test("sample trip opens a real editor with generated photos and persists curation", async ({ page }, info) => {
  await page.route("**/wails/runtime.js", (route) => route.fulfill({ contentType: "application/javascript", body: "" }))
  const errors: string[] = []
  page.on("pageerror", (error) => errors.push(error.message))
  await page.goto("/")
  await expect(page.getByRole("region", { name: "Sample workspace", exact: true })).toBeVisible()
  await expect(page.getByRole("button", { name: "Open sample trip", exact: true })).toHaveCount(0)
  await page.getByRole("link", { name: /A Kyoto afternoon/ }).click()
  await page.getByRole("link", { name: /A little paper keepsake/ }).click()
  await expect(page.getByLabel("Essay", { exact: true })).toHaveValue(/fictional afternoon/)
  const rows = page.locator(".photo-row")
  await expect(rows).toHaveCount(2)
  await expect(rows.first().locator("img")).toBeVisible()
  const order = await rows.first().locator(".photo-order").boundingBox()
  const caption = await rows.first().getByRole("textbox", { name: "Caption", exact: true }).boundingBox()
  expect(order).not.toBeNull()
  expect(caption).not.toBeNull()
  expect(order!.x + order!.width).toBeLessThanOrEqual(caption!.x)
  await rows.first().getByRole("textbox", { name: "Caption", exact: true }).fill("Edited in the isolated sample")
  await rows.first().getByRole("button", { name: "Save caption", exact: true }).click()
  await page.reload()
  await expect(rows.first().getByRole("textbox", { name: "Caption", exact: true })).toHaveValue("Edited in the isolated sample")
  await page.screenshot({ path: info.outputPath("sample-editor.png") })
  expect(errors).toEqual([])
})

test("journey detail opens the built preview in-app with comfortable header controls", async ({ page }) => {
  await page.route("**/wails/runtime.js", (route) => route.fulfill({ contentType: "application/javascript", body: "" }))
  await page.goto("/")
  const newJourney = (await page.getByRole("button", { name: "New journey", exact: true }).boundingBox())!
  expect(newJourney.height).toBeGreaterThanOrEqual(36)
  let popups = 0
  page.on("popup", () => popups++)
  await page.getByRole("link", { name: /A Kyoto afternoon/ }).click()
  await expect(page).toHaveURL(/#\/journey\/[0-9a-f-]+$/)
  const journeyURL = page.url()
  await page.getByRole("button", { name: "Preview last built site", exact: true }).click()
  const preview = page.getByRole("dialog", { name: "Last built site", exact: true })
  await expect(preview).toBeVisible()
  await expect(page.frameLocator('iframe[title="Last built site"]').locator("body")).toContainText("A Kyoto afternoon")
  const back = preview.getByRole("button", { name: "Back to studio", exact: true })
  expect((await back.boundingBox())!.height).toBeGreaterThanOrEqual(36)
  await back.click()
  await expect(preview).toBeHidden()
  expect(page.url()).toBe(journeyURL)
  expect(popups).toBe(0)
})

test("reader exposes Sun and Moon controls without changing saved appearance", async ({ page }) => {
  await page.route("**/wails/runtime.js", (route) => route.fulfill({ contentType: "application/javascript", body: "" }))
  await page.goto("/#/site")
  const before = await (await page.request.get("/api/admin/site-settings")).json()
  await page.getByRole("button", { name: "Preview last built site", exact: true }).click()
  const reader = page.frameLocator('iframe[title="Last built site"]')
  const light = reader.getByRole("button", { name: /^(Light|ライト|浅色)$/ })
  const dark = reader.getByRole("button", { name: /^(Dark|ダーク|深色)$/ })
  await expect(light.locator("svg")).toBeVisible()
  await expect(dark.locator("svg")).toBeVisible()
  await light.click()
  await expect(light).toHaveAttribute("aria-pressed", "true")
  await expect(reader.locator(".waypoints")).toHaveClass(/light/)
  await dark.click()
  await expect(dark).toHaveAttribute("aria-pressed", "true")
  await expect(reader.locator(".waypoints")).not.toHaveClass(/light/)
  expect(await (await page.request.get("/api/admin/site-settings")).json()).toEqual(before)
})

test("last-built preview stays inside the studio and preserves unsaved site inputs", async ({ page }, contextInfo) => {
  await page.route("**/wails/runtime.js", (route) => route.fulfill({ contentType: "application/javascript", body: "" }))
  let popups = 0
  page.on("popup", () => popups++)
  await page.goto("/#/site")
  const title = page.getByRole("textbox", { name: "Title", exact: true })
  await title.fill("Unsaved sample site identity")
  const before = await (await page.request.get("/api/admin/site-settings")).json()
  await page.getByRole("button", { name: "Preview last built site", exact: true }).click()
  const preview = page.getByRole("dialog", { name: "Last built site", exact: true })
  await expect(preview).toBeVisible()
  await expect(preview).toContainText("Unsaved edits are not included")
  const frame = preview.locator("iframe")
  await expect(frame).toHaveAttribute("src", /^http:\/\/127\.0\.0\.1:\d+\/$/)
  await expect(page.frameLocator('iframe[title="Last built site"]').locator("body")).toContainText("A Kyoto afternoon")
  await page.screenshot({ path: contextInfo.outputPath("in-app-preview.png") })
  await preview.getByRole("button", { name: "Back to studio", exact: true }).click()
  await expect(preview).toBeHidden()
  await expect(title).toHaveValue("Unsaved sample site identity")
  expect(await (await page.request.get("/api/admin/site-settings")).json()).toEqual(before)
  expect(popups).toBe(0)
})
