// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Journal struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

type Journey struct {
	ID             uuid.UUID
	JournalID      uuid.UUID
	Slug           string
	SourceRef      pgtype.Text
	Title          string
	Place          string
	Country        pgtype.Text
	Region         pgtype.Text
	DateStart      pgtype.Date
	DateEnd        pgtype.Date
	GpsRoute       interface{}
	AuthoredFields []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Memento struct {
	ID             uuid.UUID
	JourneyID      uuid.UUID
	Kind           string
	Seq            int32
	OccurredAt     pgtype.Timestamptz
	OccurredTz     string
	Geom           interface{}
	Title          string
	Place          string
	Vendor         pgtype.Text
	Essay          pgtype.Text
	PriceAmount    pgtype.Int8
	PriceCurrency  pgtype.Text
	KindData       []byte
	SourceRef      pgtype.Text
	AuthoredFields []string
	OrphanedAt     pgtype.Timestamptz
	State          string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type MementoPhoto struct {
	ID          uuid.UUID
	MementoID   uuid.UUID
	ObjectKey   string
	ContentHash string
	Caption     pgtype.Text
	Seq         int32
	TakenAt     pgtype.Timestamptz
	SourceRef   pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type TransitLeg struct {
	ID          uuid.UUID
	JourneyID   uuid.UUID
	Seq         int32
	OriginLabel pgtype.Text
	DestLabel   pgtype.Text
	Geom        interface{}
	CreatedAt   pgtype.Timestamptz
}

type Translation struct {
	ID         uuid.UUID
	OwnerType  string
	OwnerID    uuid.UUID
	Lang       string
	Field      string
	Value      string
	Provenance string
	UpdatedAt  pgtype.Timestamptz
}
