// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJournal = `-- name: CreateJournal :exec
INSERT INTO journal (id, created_at) VALUES ($1, $2)
`

const createImportRun = `-- name: CreateImportRun :exec
INSERT INTO import_runs (id, source_system, started_at, status, error_message)
VALUES ($1, $2, $3, $4, $5)
`

type CreateImportRunParams struct {
	ID           uuid.UUID
	SourceSystem string
	StartedAt    pgtype.Timestamptz
	Status       string
	ErrorMessage pgtype.Text
}

func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) error {
	_, err := q.db.Exec(ctx, createImportRun, arg.ID, arg.SourceSystem, arg.StartedAt, arg.Status, arg.ErrorMessage)
	return err
}

const finishImportRun = `-- name: FinishImportRun :exec
UPDATE import_runs
SET status = $2, finished_at = $3, error_message = $4
WHERE id = $1
`

type FinishImportRunParams struct {
	ID           uuid.UUID
	Status       string
	FinishedAt   pgtype.Timestamptz
	ErrorMessage pgtype.Text
}

func (q *Queries) FinishImportRun(ctx context.Context, arg FinishImportRunParams) error {
	_, err := q.db.Exec(ctx, finishImportRun, arg.ID, arg.Status, arg.FinishedAt, arg.ErrorMessage)
	return err
}

const recordSourceObservation = `-- name: RecordSourceObservation :exec
INSERT INTO source_observations (
    id, run_id, source_system, source_external_id, kind, observed_at,
    confidence, payload, changed, orphaned_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    COALESCE((
        SELECT payload IS DISTINCT FROM $8::jsonb
        FROM source_observations
        WHERE source_system = $3 AND source_external_id = $4
        ORDER BY observed_at DESC, created_at DESC
        LIMIT 1
    ), FALSE), NULL
)
ON CONFLICT (run_id, source_system, source_external_id) DO UPDATE SET
    kind = EXCLUDED.kind,
    observed_at = EXCLUDED.observed_at,
    confidence = EXCLUDED.confidence,
    payload = EXCLUDED.payload,
    changed = EXCLUDED.changed,
    orphaned_at = NULL
`

type RecordSourceObservationParams struct {
	ID               uuid.UUID
	RunID            uuid.UUID
	SourceSystem     string
	SourceExternalID string
	Kind             string
	ObservedAt       pgtype.Timestamptz
	Confidence       float64
	Payload          []byte
}

func (q *Queries) RecordSourceObservation(ctx context.Context, arg RecordSourceObservationParams) error {
	_, err := q.db.Exec(ctx, recordSourceObservation,
		arg.ID, arg.RunID, arg.SourceSystem, arg.SourceExternalID, arg.Kind,
		arg.ObservedAt, arg.Confidence, arg.Payload,
	)
	return err
}

const markMissingSourceObservations = `-- name: MarkMissingSourceObservations :exec
UPDATE source_observations
SET orphaned_at = NOW()
WHERE source_system = $2
  AND run_id <> $1
  AND orphaned_at IS NULL
  AND NOT (source_external_id = ANY($3::text[]))
`

type MarkMissingSourceObservationsParams struct {
	RunID           uuid.UUID
	SourceSystem    string
	SeenExternalIDs []string
}

func (q *Queries) MarkMissingSourceObservations(ctx context.Context, arg MarkMissingSourceObservationsParams) error {
	_, err := q.db.Exec(ctx, markMissingSourceObservations, arg.RunID, arg.SourceSystem, arg.SeenExternalIDs)
	return err
}

const resetMockJournal = `-- name: ResetMockJournal :exec
DELETE FROM journal WHERE id = $1
`

func (q *Queries) ResetMockJournal(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetMockJournal, id)
	return err
}

type CreateJournalParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) error {
	_, err := q.db.Exec(ctx, createJournal, arg.ID, arg.CreatedAt)
	return err
}

const createTransitLeg = `-- name: CreateTransitLeg :exec
INSERT INTO transit_legs (
    id, journey_id, seq, origin_label, dest_label, geom
) VALUES (
    $1, $2, $3, $4, $5,
    ST_Segmentize(
        ST_MakeLine(
            ST_SetSRID(ST_MakePoint($6::float8, $7::float8), 4326),
            ST_SetSRID(ST_MakePoint($8::float8, $9::float8), 4326)
        )::geography,
        $10::float8
    )::geometry
)
`

type CreateTransitLegParams struct {
	ID             uuid.UUID
	JourneyID      uuid.UUID
	Seq            int32
	OriginLabel    pgtype.Text
	DestLabel      pgtype.Text
	OriginLng      float64
	OriginLat      float64
	DestLng        float64
	DestLat        float64
	SegmentLengthM float64
}

// Build the great-circle arc once, at insert: ST_MakeLine of the two endpoints,
// densified along the geodesic by ST_Segmentize on geography ($10 = max segment
// length in metres), cast back to a 4326 LineString for the column (ADR 0009).
func (q *Queries) CreateTransitLeg(ctx context.Context, arg CreateTransitLegParams) error {
	_, err := q.db.Exec(ctx, createTransitLeg,
		arg.ID,
		arg.JourneyID,
		arg.Seq,
		arg.OriginLabel,
		arg.DestLabel,
		arg.OriginLng,
		arg.OriginLat,
		arg.DestLng,
		arg.DestLat,
		arg.SegmentLengthM,
	)
	return err
}

const deleteTransitLeg = `-- name: DeleteTransitLeg :exec
DELETE FROM transit_legs WHERE id = $1
`

func (q *Queries) DeleteTransitLeg(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransitLeg, id)
	return err
}

const getDisplayRoute = `-- name: GetDisplayRoute :one
SELECT ST_AsBinary(
    ST_Multi(ST_CollectionExtract(
        ST_Collect(
            j.gps_route,
            (SELECT ST_Collect(l.geom) FROM transit_legs l WHERE l.journey_id = j.id)
        ), 2))
) AS route_wkb
FROM journeys j
WHERE j.id = $1
`

// Union-at-read: the display route is the Dawarich track combined with every
// authored transit leg, composed on the fly (data-model.md D2). gps_route itself
// is never mutated. Returns NULL WKB when the journey has neither track nor legs.
func (q *Queries) GetDisplayRoute(ctx context.Context, id uuid.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, getDisplayRoute, id)
	var route_wkb interface{}
	err := row.Scan(&route_wkb)
	return route_wkb, err
}

const getJournal = `-- name: GetJournal :one
SELECT id, created_at FROM journal WHERE id = $1
`

func (q *Queries) GetJournal(ctx context.Context, id uuid.UUID) (Journal, error) {
	row := q.db.QueryRow(ctx, getJournal, id)
	var i Journal
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const getJourney = `-- name: GetJourney :one
SELECT id, journal_id, slug, source_ref, title, place, country, region, date_start, date_end, ST_AsBinary(gps_route) AS gps_route_wkb, authored_fields, created_at, updated_at
FROM journeys
WHERE id = $1
`

type GetJourneyRow struct {
	ID             uuid.UUID
	JournalID      uuid.UUID
	Slug           string
	SourceRef      pgtype.Text
	Title          string
	Place          string
	Country        pgtype.Text
	Region         pgtype.Text
	DateStart      pgtype.Date
	DateEnd        pgtype.Date
	GpsRouteWkb    interface{}
	AuthoredFields []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetJourney(ctx context.Context, id uuid.UUID) (GetJourneyRow, error) {
	row := q.db.QueryRow(ctx, getJourney, id)
	var i GetJourneyRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Slug,
		&i.SourceRef,
		&i.Title,
		&i.Place,
		&i.Country,
		&i.Region,
		&i.DateStart,
		&i.DateEnd,
		&i.GpsRouteWkb,
		&i.AuthoredFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJourneyBySlug = `-- name: GetJourneyBySlug :one
SELECT id, journal_id, slug, source_ref, title, place, country, region, date_start, date_end, ST_AsBinary(gps_route) AS gps_route_wkb, authored_fields, created_at, updated_at
FROM journeys
WHERE slug = $1
`

type GetJourneyBySlugRow struct {
	ID             uuid.UUID
	JournalID      uuid.UUID
	Slug           string
	SourceRef      pgtype.Text
	Title          string
	Place          string
	Country        pgtype.Text
	Region         pgtype.Text
	DateStart      pgtype.Date
	DateEnd        pgtype.Date
	GpsRouteWkb    interface{}
	AuthoredFields []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) GetJourneyBySlug(ctx context.Context, slug string) (GetJourneyBySlugRow, error) {
	row := q.db.QueryRow(ctx, getJourneyBySlug, slug)
	var i GetJourneyBySlugRow
	err := row.Scan(
		&i.ID,
		&i.JournalID,
		&i.Slug,
		&i.SourceRef,
		&i.Title,
		&i.Place,
		&i.Country,
		&i.Region,
		&i.DateStart,
		&i.DateEnd,
		&i.GpsRouteWkb,
		&i.AuthoredFields,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMemento = `-- name: GetMemento :one
SELECT id, journey_id, kind, seq, occurred_at, occurred_tz, ST_AsBinary(geom) AS geom_wkb, title, place, vendor, essay, price_amount, price_currency, kind_data, source_system, source_external_id, source_ref, authored_fields, orphaned_at, state, revision, created_at, updated_at
FROM mementos
WHERE id = $1
`

type GetMementoRow struct {
	ID               uuid.UUID
	JourneyID        uuid.UUID
	Kind             string
	Seq              int32
	OccurredAt       pgtype.Timestamptz
	OccurredTz       string
	GeomWkb          interface{}
	Title            string
	Place            string
	Vendor           pgtype.Text
	Essay            pgtype.Text
	PriceAmount      pgtype.Int8
	PriceCurrency    pgtype.Text
	KindData         []byte
	SourceSystem     pgtype.Text
	SourceExternalID pgtype.Text
	SourceRef        pgtype.Text
	AuthoredFields   []string
	OrphanedAt       pgtype.Timestamptz
	State            string
	Revision         int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) GetMemento(ctx context.Context, id uuid.UUID) (GetMementoRow, error) {
	row := q.db.QueryRow(ctx, getMemento, id)
	var i GetMementoRow
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.Kind,
		&i.Seq,
		&i.OccurredAt,
		&i.OccurredTz,
		&i.GeomWkb,
		&i.Title,
		&i.Place,
		&i.Vendor,
		&i.Essay,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.KindData,
		&i.SourceSystem,
		&i.SourceExternalID,
		&i.SourceRef,
		&i.AuthoredFields,
		&i.OrphanedAt,
		&i.State,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMementoBySourceIdentity = `-- name: GetMementoBySourceIdentity :one
SELECT id, journey_id, kind, seq, occurred_at, occurred_tz, ST_AsBinary(geom) AS geom_wkb, title, place, vendor, essay, price_amount, price_currency, kind_data, source_system, source_external_id, source_ref, authored_fields, orphaned_at, state, revision, created_at, updated_at
FROM mementos
WHERE source_system = $1 AND source_external_id = $2
`

func (q *Queries) GetMementoBySourceIdentity(ctx context.Context, sourceSystem string, sourceExternalID string) (GetMementoRow, error) {
	row := q.db.QueryRow(ctx, getMementoBySourceIdentity, sourceSystem, sourceExternalID)
	var i GetMementoRow
	err := row.Scan(
		&i.ID, &i.JourneyID, &i.Kind, &i.Seq, &i.OccurredAt, &i.OccurredTz,
		&i.GeomWkb, &i.Title, &i.Place, &i.Vendor, &i.Essay, &i.PriceAmount,
		&i.PriceCurrency, &i.KindData, &i.SourceSystem, &i.SourceExternalID,
		&i.SourceRef, &i.AuthoredFields, &i.OrphanedAt, &i.State, &i.Revision,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, memento_id, object_key, content_hash, caption, seq, taken_at, source_ref, created_at
FROM memento_photos
WHERE id = $1
`

func (q *Queries) GetPhoto(ctx context.Context, id uuid.UUID) (MementoPhoto, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i MementoPhoto
	err := row.Scan(
		&i.ID,
		&i.MementoID,
		&i.ObjectKey,
		&i.ContentHash,
		&i.Caption,
		&i.Seq,
		&i.TakenAt,
		&i.SourceRef,
		&i.CreatedAt,
	)
	return i, err
}

const listJourneys = `-- name: ListJourneys :many
SELECT id, journal_id, slug, source_ref, title, place, country, region, date_start, date_end, ST_AsBinary(gps_route) AS gps_route_wkb, authored_fields, created_at, updated_at
FROM journeys
ORDER BY date_start DESC
`

type ListJourneysRow struct {
	ID             uuid.UUID
	JournalID      uuid.UUID
	Slug           string
	SourceRef      pgtype.Text
	Title          string
	Place          string
	Country        pgtype.Text
	Region         pgtype.Text
	DateStart      pgtype.Date
	DateEnd        pgtype.Date
	GpsRouteWkb    interface{}
	AuthoredFields []string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) ListJourneys(ctx context.Context) ([]ListJourneysRow, error) {
	rows, err := q.db.Query(ctx, listJourneys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJourneysRow
	for rows.Next() {
		var i ListJourneysRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.Slug,
			&i.SourceRef,
			&i.Title,
			&i.Place,
			&i.Country,
			&i.Region,
			&i.DateStart,
			&i.DateEnd,
			&i.GpsRouteWkb,
			&i.AuthoredFields,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMementosByJourney = `-- name: ListMementosByJourney :many
SELECT id, journey_id, kind, seq, occurred_at, occurred_tz, ST_AsBinary(geom) AS geom_wkb, title, place, vendor, essay, price_amount, price_currency, kind_data, source_system, source_external_id, source_ref, authored_fields, orphaned_at, state, revision, created_at, updated_at
FROM mementos
WHERE journey_id = $1
ORDER BY seq ASC, occurred_at ASC
`

type ListMementosByJourneyRow struct {
	ID               uuid.UUID
	JourneyID        uuid.UUID
	Kind             string
	Seq              int32
	OccurredAt       pgtype.Timestamptz
	OccurredTz       string
	GeomWkb          interface{}
	Title            string
	Place            string
	Vendor           pgtype.Text
	Essay            pgtype.Text
	PriceAmount      pgtype.Int8
	PriceCurrency    pgtype.Text
	KindData         []byte
	SourceSystem     pgtype.Text
	SourceExternalID pgtype.Text
	SourceRef        pgtype.Text
	AuthoredFields   []string
	OrphanedAt       pgtype.Timestamptz
	State            string
	Revision         int64
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) ListMementosByJourney(ctx context.Context, journeyID uuid.UUID) ([]ListMementosByJourneyRow, error) {
	rows, err := q.db.Query(ctx, listMementosByJourney, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMementosByJourneyRow
	for rows.Next() {
		var i ListMementosByJourneyRow
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.Kind,
			&i.Seq,
			&i.OccurredAt,
			&i.OccurredTz,
			&i.GeomWkb,
			&i.Title,
			&i.Place,
			&i.Vendor,
			&i.Essay,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.KindData,
			&i.SourceSystem,
			&i.SourceExternalID,
			&i.SourceRef,
			&i.AuthoredFields,
			&i.OrphanedAt,
			&i.State,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPhotosByMemento = `-- name: ListPhotosByMemento :many
SELECT id, memento_id, object_key, content_hash, caption, seq, taken_at, source_ref, created_at
FROM memento_photos
WHERE memento_id = $1
ORDER BY seq ASC
`

func (q *Queries) ListPhotosByMemento(ctx context.Context, mementoID uuid.UUID) ([]MementoPhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosByMemento, mementoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MementoPhoto
	for rows.Next() {
		var i MementoPhoto
		if err := rows.Scan(
			&i.ID,
			&i.MementoID,
			&i.ObjectKey,
			&i.ContentHash,
			&i.Caption,
			&i.Seq,
			&i.TakenAt,
			&i.SourceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransitLegsByJourney = `-- name: ListTransitLegsByJourney :many
SELECT id, journey_id, seq, origin_label, dest_label, ST_AsBinary(geom) AS geom_wkb, created_at
FROM transit_legs
WHERE journey_id = $1
ORDER BY seq ASC, created_at ASC
`

type ListTransitLegsByJourneyRow struct {
	ID          uuid.UUID
	JourneyID   uuid.UUID
	Seq         int32
	OriginLabel pgtype.Text
	DestLabel   pgtype.Text
	GeomWkb     interface{}
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) ListTransitLegsByJourney(ctx context.Context, journeyID uuid.UUID) ([]ListTransitLegsByJourneyRow, error) {
	rows, err := q.db.Query(ctx, listTransitLegsByJourney, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransitLegsByJourneyRow
	for rows.Next() {
		var i ListTransitLegsByJourneyRow
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.Seq,
			&i.OriginLabel,
			&i.DestLabel,
			&i.GeomWkb,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTranslations = `-- name: ListTranslations :many
SELECT id, owner_type, owner_id, lang, field, value, provenance, updated_at
FROM translations
WHERE owner_type = $1 AND owner_id = $2
`

type ListTranslationsParams struct {
	OwnerType string
	OwnerID   uuid.UUID
}

func (q *Queries) ListTranslations(ctx context.Context, arg ListTranslationsParams) ([]Translation, error) {
	rows, err := q.db.Query(ctx, listTranslations, arg.OwnerType, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Translation
	for rows.Next() {
		var i Translation
		if err := rows.Scan(
			&i.ID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Lang,
			&i.Field,
			&i.Value,
			&i.Provenance,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapToRoute = `-- name: SnapToRoute :one
SELECT ST_AsBinary(
    ST_ClosestPoint(
        ST_CollectionExtract(
            ST_Collect(
                j.gps_route,
                (SELECT ST_Collect(l.geom) FROM transit_legs l WHERE l.journey_id = j.id)
            ), 2),
        ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)
    )
) AS snapped_wkb
FROM journeys j
WHERE j.id = $3
`

type SnapToRouteParams struct {
	Lng       float64
	Lat       float64
	JourneyID uuid.UUID
}

// Proximity snap of an arbitrary point onto the composed route (track ∪ legs).
// ST_ClosestPoint is MultiLineString-safe (unlike ST_LineLocatePoint, which
// rejects multilinestrings). Returns NULL WKB when the route is empty.
func (q *Queries) SnapToRoute(ctx context.Context, arg SnapToRouteParams) (interface{}, error) {
	row := q.db.QueryRow(ctx, snapToRoute, arg.Lng, arg.Lat, arg.JourneyID)
	var snapped_wkb interface{}
	err := row.Scan(&snapped_wkb)
	return snapped_wkb, err
}

const upsertJourney = `-- name: UpsertJourney :exec
INSERT INTO journeys (
    id, journal_id, slug, source_ref, title, place, country, region, date_start, date_end, gps_route, authored_fields, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, ST_GeomFromWKB($11, 4326), $12, NOW(), NOW()
) ON CONFLICT (id) DO UPDATE SET
    slug = CASE WHEN NOT (journeys.authored_fields @> ARRAY['slug']) THEN EXCLUDED.slug ELSE journeys.slug END,
    title = CASE WHEN NOT (journeys.authored_fields @> ARRAY['title']) THEN EXCLUDED.title ELSE journeys.title END,
    place = CASE WHEN NOT (journeys.authored_fields @> ARRAY['place']) THEN EXCLUDED.place ELSE journeys.place END,
    country = CASE WHEN NOT (journeys.authored_fields @> ARRAY['country']) THEN EXCLUDED.country ELSE journeys.country END,
    region = CASE WHEN NOT (journeys.authored_fields @> ARRAY['region']) THEN EXCLUDED.region ELSE journeys.region END,
    date_start = CASE WHEN NOT (journeys.authored_fields @> ARRAY['date_start']) THEN EXCLUDED.date_start ELSE journeys.date_start END,
    date_end = CASE WHEN NOT (journeys.authored_fields @> ARRAY['date_end']) THEN EXCLUDED.date_end ELSE journeys.date_end END,
    gps_route = CASE WHEN NOT (journeys.authored_fields @> ARRAY['gps_route']) THEN EXCLUDED.gps_route ELSE journeys.gps_route END,
    source_ref = EXCLUDED.source_ref,
    authored_fields = EXCLUDED.authored_fields,
    updated_at = NOW()
`

type UpsertJourneyParams struct {
	ID             uuid.UUID
	JournalID      uuid.UUID
	Slug           string
	SourceRef      pgtype.Text
	Title          string
	Place          string
	Country        pgtype.Text
	Region         pgtype.Text
	DateStart      pgtype.Date
	DateEnd        pgtype.Date
	StGeomfromwkb  interface{}
	AuthoredFields []string
}

func (q *Queries) UpsertJourney(ctx context.Context, arg UpsertJourneyParams) error {
	_, err := q.db.Exec(ctx, upsertJourney,
		arg.ID,
		arg.JournalID,
		arg.Slug,
		arg.SourceRef,
		arg.Title,
		arg.Place,
		arg.Country,
		arg.Region,
		arg.DateStart,
		arg.DateEnd,
		arg.StGeomfromwkb,
		arg.AuthoredFields,
	)
	return err
}

const upsertMemento = `-- name: UpsertMemento :exec
INSERT INTO mementos (
    id, journey_id, kind, seq, occurred_at, occurred_tz, geom, title, place, vendor, essay, price_amount, price_currency, kind_data, source_system, source_external_id, source_ref, authored_fields, orphaned_at, state, revision, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, ST_GeomFromWKB($7, 4326), $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, COALESCE($21, 1), NOW(), NOW()
) ON CONFLICT (id) DO UPDATE SET
    kind = CASE WHEN NOT (mementos.authored_fields @> ARRAY['kind']) THEN EXCLUDED.kind ELSE mementos.kind END,
    seq = CASE WHEN NOT (mementos.authored_fields @> ARRAY['seq']) THEN EXCLUDED.seq ELSE mementos.seq END,
    occurred_at = CASE WHEN NOT (mementos.authored_fields @> ARRAY['occurred_at']) THEN EXCLUDED.occurred_at ELSE mementos.occurred_at END,
    occurred_tz = CASE WHEN NOT (mementos.authored_fields @> ARRAY['occurred_tz']) THEN EXCLUDED.occurred_tz ELSE mementos.occurred_tz END,
    geom = CASE WHEN NOT (mementos.authored_fields @> ARRAY['geom']) THEN EXCLUDED.geom ELSE mementos.geom END,
    title = CASE WHEN NOT (mementos.authored_fields @> ARRAY['title']) THEN EXCLUDED.title ELSE mementos.title END,
    place = CASE WHEN NOT (mementos.authored_fields @> ARRAY['place']) THEN EXCLUDED.place ELSE mementos.place END,
    vendor = CASE WHEN NOT (mementos.authored_fields @> ARRAY['vendor']) THEN EXCLUDED.vendor ELSE mementos.vendor END,
    essay = CASE WHEN NOT (mementos.authored_fields @> ARRAY['essay']) THEN EXCLUDED.essay ELSE mementos.essay END,
    price_amount = CASE WHEN NOT (mementos.authored_fields @> ARRAY['price_amount']) THEN EXCLUDED.price_amount ELSE mementos.price_amount END,
    price_currency = CASE WHEN NOT (mementos.authored_fields @> ARRAY['price_currency']) THEN EXCLUDED.price_currency ELSE mementos.price_currency END,
    kind_data = CASE WHEN NOT (mementos.authored_fields @> ARRAY['kind_data']) THEN EXCLUDED.kind_data ELSE mementos.kind_data END,
    source_system = EXCLUDED.source_system,
    source_external_id = EXCLUDED.source_external_id,
    source_ref = EXCLUDED.source_ref,
    orphaned_at = EXCLUDED.orphaned_at,
    state = EXCLUDED.state,
    revision = mementos.revision + 1,
    authored_fields = EXCLUDED.authored_fields,
    updated_at = NOW()
WHERE $22::bigint IS NULL OR mementos.revision = $22
`

type UpsertMementoParams struct {
	ID               uuid.UUID
	JourneyID        uuid.UUID
	Kind             string
	Seq              int32
	OccurredAt       pgtype.Timestamptz
	OccurredTz       string
	StGeomfromwkb    interface{}
	Title            string
	Place            string
	Vendor           pgtype.Text
	Essay            pgtype.Text
	PriceAmount      pgtype.Int8
	PriceCurrency    pgtype.Text
	KindData         []byte
	SourceSystem     pgtype.Text
	SourceExternalID pgtype.Text
	SourceRef        pgtype.Text
	AuthoredFields   []string
	OrphanedAt       pgtype.Timestamptz
	State            string
	Revision         pgtype.Int8
	ExpectedRevision pgtype.Int8
}

func (q *Queries) UpsertMemento(ctx context.Context, arg UpsertMementoParams) error {
	tag, err := q.db.Exec(ctx, upsertMemento,
		arg.ID,
		arg.JourneyID,
		arg.Kind,
		arg.Seq,
		arg.OccurredAt,
		arg.OccurredTz,
		arg.StGeomfromwkb,
		arg.Title,
		arg.Place,
		arg.Vendor,
		arg.Essay,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.KindData,
		arg.SourceSystem,
		arg.SourceExternalID,
		arg.SourceRef,
		arg.AuthoredFields,
		arg.OrphanedAt,
		arg.State,
		arg.Revision,
		arg.ExpectedRevision,
	)
	if err != nil {
		return err
	}
	if tag.RowsAffected() == 0 {
		return pgx.ErrNoRows
	}
	return nil
}

const upsertPhoto = `-- name: UpsertPhoto :exec
INSERT INTO memento_photos (
    id, memento_id, object_key, content_hash, caption, seq, taken_at, source_ref, created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW()
) ON CONFLICT (id) DO UPDATE SET
    memento_id = EXCLUDED.memento_id,
    object_key = EXCLUDED.object_key,
    content_hash = EXCLUDED.content_hash,
    caption = EXCLUDED.caption,
    seq = EXCLUDED.seq,
    taken_at = EXCLUDED.taken_at,
    source_ref = EXCLUDED.source_ref
`

type UpsertPhotoParams struct {
	ID          uuid.UUID
	MementoID   uuid.UUID
	ObjectKey   string
	ContentHash string
	Caption     pgtype.Text
	Seq         int32
	TakenAt     pgtype.Timestamptz
	SourceRef   pgtype.Text
}

func (q *Queries) UpsertPhoto(ctx context.Context, arg UpsertPhotoParams) error {
	_, err := q.db.Exec(ctx, upsertPhoto,
		arg.ID,
		arg.MementoID,
		arg.ObjectKey,
		arg.ContentHash,
		arg.Caption,
		arg.Seq,
		arg.TakenAt,
		arg.SourceRef,
	)
	if err != nil {
		return err
	}
	return nil
}

const upsertTranslation = `-- name: UpsertTranslation :exec
INSERT INTO translations (
    id, owner_type, owner_id, lang, field, value, provenance, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
) ON CONFLICT (owner_type, owner_id, lang, field) DO UPDATE SET
    value = CASE WHEN translations.provenance = 'machine' OR EXCLUDED.provenance = 'authored' THEN EXCLUDED.value ELSE translations.value END,
    provenance = CASE WHEN translations.provenance = 'machine' OR EXCLUDED.provenance = 'authored' THEN EXCLUDED.provenance ELSE translations.provenance END,
    updated_at = NOW()
`

type UpsertTranslationParams struct {
	ID         uuid.UUID
	OwnerType  string
	OwnerID    uuid.UUID
	Lang       string
	Field      string
	Value      string
	Provenance string
}

func (q *Queries) UpsertTranslation(ctx context.Context, arg UpsertTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertTranslation,
		arg.ID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Lang,
		arg.Field,
		arg.Value,
		arg.Provenance,
	)
	return err
}
